version: 2
updates:
  - package-ecosystem: "npm" # Possible values: "bundler", "cargo", "composer", "docker", "elm", "gitsubmodule", "github-actions", "go", "gradle", "hex", "maven", "mix", "npm", "nuget", "pip", "terraform"
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
